apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: by3ncpqlz-go 
  janus-idp.io/tekton: by3ncpqlz-go
  backstage.io/kubernetes-id: by3ncpqlz-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: by3ncpqlz-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml